### ISSUE TITLE
has problems with `applicationContext.getString`

### ISSUE THREAD

**Issue by adherencegoo** [B3nedikt/restring#102]
There's no way to tamper `Resources` in `Application`.
At least, `RestringResources` should be public so that I can override `Application.getResources` with it.

**Comment by B3nedikt** [comment]
This is intentional, if you want to modify Resources, just create a new context wrapper around the resources instance provided by the context wrapped by Restring. So in your `Application` something like this:
```kotlin
YourContextWrapper.wrap(Restring.wrapContext(this)).getResources()
```
Now just overwrite `getResources` in your `ContextWrapper` with your own `Resources`, and delegate all calls except what you want to modify to the one from the baseContext. Do not try to extend from `RestringResources` or any other custom 'Resources* instance, always wrap and delegate like it is done in this library. If not you may run into all kinds of problems.

**Comment by adherencegoo** [comment]
The problem is that the following code creates infinite loop.
The `RestringContextWrapper` will use `super.getResources`, and lead to `MyApplication.getResources()` eventually

// in Application
```
private val myResources: Resources by lazy {
    Restring.wrapContext(this).getResources()
}

override fun getResources() = myResources
```

**Comment by B3nedikt** [comment]
In short it already is attached to the Application, when you call `Restring.wrapContext(this).getResources()` in the application you already get the `Resources` of the `Application`. The call to `super.getResources` is necessary so we can delegate. I don`t know what you want to achieve here. Can you post a more complete example of why you want to do this? You can also fork this repository and modify the code to demonstrate your use case.

**Comment by adherencegoo** [comment]
My usage is quite simple, just using `NCWApplication.getString(...)`
Because the project I'm working on massively uses the static `NCWApplication` to get strings, it's unrealistic to replace all application context with activity context.

1. And, as what I said above, `attachBaseContext` didn't work for `Application`
2. The following code produces infinite loop

```
private val myResources: Resources by lazy {
    Restring.wrapContext(this).getResources()
}

override fun getResources() = myResources
```

<img width="658" alt="Screen Shot 2022-05-10 at 8 36 59 PM" src="https://user-images.githubusercontent.com/8948922/167630529-14181cfb-10f1-4628-b9f2-181e49a10a59.png">

Because [the following](https://github.com/B3nedikt/restring/blob/master/restring/src/main/java/dev/b3nedikt/restring/internal/RestringContextWrapper.kt) `super.getResources()` will eventually use `base.getResources()` --> `NCWApplication.getResources`

```
internal class RestringContextWrapper private constructor(
        base: Context,
        stringRepository: StringRepository
) : ContextWrapper(base) {

    private val res: Resources by lazy {
        val baseResources = super.getResources()
        RestringResources(baseResources, stringRepository, this)
    }
```

---
**Proposed solution**

1. Make `RestringResources` public, so that I can give it the true `super.getResources()`
In `NCWApplication`
```
private val myResources: Resources by lazy {
    RestringResources(super.getResources(), Restring.stringRepository, this)
}

override fun getResources() = myResources
```

2. Or, maybe you can come up with another approach to attach `RestringResources` to `Application`

**Comment by adherencegoo** [comment]
I think it damages the encapsulation, may not be a good idea 🤔
And, I even have to do the similar things for string array and quantity string

I guess that using application context to get strings is not a rare case, do you have other installation suggestion on `Application`?

**Comment by B3nedikt** [comment]
It is rare I think, I can't think of any good use case for it. But anyway try reflection:
```kotlin
Class.forName("dev.b3nedikt.restring.internal.RestringResources")
            .constructors[0]
            .newInstance(super.getResources(), Restring.stringRepository, this) as Resources
```
You need to do a `Restring.init(...)` before and it should work :)

**Comment by adherencegoo** [comment]
I don't think it's worth to do reflection for this... I would rather fork this project
There would be more security issues from proguard and other 3rd-party anti-hack libs if using reflection.

In my opinions, both `Activity` and `Application` extend `Context`, both have the `getResources()` function. So, "attaching `RestringResources`" should be applicable for both of them. Not only for some rare (you think) cases, but also honor the parent class.

Really appreciate the above discussion. Thx

**Comment by B3nedikt** [comment]
You're welcome :) A fork sounds good, if more people request something like this I will look if I find a solution for the main lib.
