### ISSUE TITLE
Manifest Placeholder

### ISSUE THREAD

**Issue by davisoqt** [B3nedikt/restring#109]
I have a manifest placeholder string resource wich i need to override at runtime. This library override the real value of the string resource in the next launch of the app once the string is changed with the library?

**Comment by B3nedikt** [comment]
No,  [manifestPlaceholders](https://developer.android.com/studio/build/manage-manifests#inject_build_variables_into_the_manifest) are resolved by gradle at compile time. You cannot overwrite it at runtime. Why would you need to do that?

**Comment by davisoqt** [comment]
My bad, i refer to string resource of admob_id in manifest metadata.
Because y need monetize via dashboard my app and i need load different
admob_id. So admob initialization occurs in manifest, not in code. My new
question is. when i change the string resource via your library that change
persists when the app opens the next time?.  You develop a fantastic
library +10.

**Comment by B3nedikt** [comment]
Yeah, it persists :)

**Comment by davisoqt** [comment]
Awesome, thanks!

**Comment by B3nedikt** [comment]
You're welcome :)
