### ISSUE TITLE
TypedArray#getText does not return translated string for custom attribute in custom view

### ISSUE THREAD

**Issue by dzielins42** [B3nedikt/restring#111]
Hello,

I have a custom view with custom attribute defined as
`<attr name="header_text" format="string|reference" />`

In my custom view I try to read the value using `TypedArray` as follows:

```
  init {
    context.obtainStyledAttributes(
      attrs, R.styleable.MyCustomView, defStyleAttr, R.style.MyCustomView
    ).use { typedArray ->
      // ...
      header = typedArray.getText(R.styleable.MyCustomView_header_text)
      // ...
    }
    // ...
  }
```

`header_text` value is set in XML as follows using `app:header_text="@string/string_ref"`

Resulting `header` value is incorrect. It's taken from `strings.xml`, not Restring.

I've debugged it and string retrieval process skips Restring altogether.

Application uses custom `StringRepository` to get translations from translation file. This file is downloaded during application startup. Basically, `strings.xml` contains keys to key-value pairs stored in the file. However, it's not the issue because call to `getString(R.string.string_ref)` returns correct value. Similarly, setting `android:text="@string/string_ref"` in a `TextView` results in correct text being displayed.

The workaround I use is to simply set `header` manually in `Fragment`:
```
view.header = getString(R.string.string_ref)
```

However, I would appreciate, if Restring would work correctly with given use case right in `MyCustomView#init`

**Comment by B3nedikt** [comment]
This is possible to implement, but would take quite a bit of work. In short you would need to modify the 'obtainStyledAttributes(...)' method of the 'ResourcesWrapper', to return a TypedArray which returns texts from the 'StringRepository'. This custom TypedArray would need to overwrite the 'getText()' method.

In short you are looking at 1-2 days of programming, which I don't have the time right now to do on the side ;) If this feature is important to you, feel free to implement it and submit a PR though :)

I think your workaround is fine, another alternative would be a custom Reword 'ViewTransformer', just look at my repository for an example.

**Comment by B3nedikt** [comment]
Closing for now, feel free to reopen if you want to implement it.

**Comment by abdelmalek-roshdi** [comment]
@dzielins42 I had the same issue but was able to work around it like so 

``` kotlin
fun TypedArray.getStringFromResources(@StyleableRes styleabResId: Int): String? {

    return getResourceId(styleabResId, 0).takeIf { it != 0 }?.run {
    
        resources.getString(this)
        
    }
 
}
```

``` kotlin
init {
    context.obtainStyledAttributes(
      attrs, R.styleable.MyCustomView, defStyleAttr, R.style.MyCustomView
    ).use { typedArray -> 
      header = typedArray. getStringFromResources(R.styleable.MyCustomView_header_text)
    }
  }
 ```
 
 @B3nedikt for your suggestion to make a custom `TypedArray` it was not possible as its constructor is package private so you can't call its super and inherit from it

**Comment by MirkoWu** [comment]
> This is possible to implement, but would take quite a bit of work. In short you would need to modify the `obtainTypedArray(...)` method of the `ResourcesWrapper`, to return a `TypedArray` which returns texts from the `StringRepository`. This custom `TypedArray` would need to overwrite the `getText()` method.
> 
> In short you are looking at 1-2 days of programming, which I don't have the time right now to do on the side ;) If this feature is important to you, feel free to implement it and submit a PR though :)
> 
> I think your workaround is fine, another alternative would be a custom Reword `ViewTransformer`, just look at my repository for an example.

hello,May I ask if this feature is currently implemented?

**Comment by MirkoWu** [comment]
> @abdelmalek-roshdi This is not a problem, you just need to set the package correctly. Something like this should do it:
> 
> ```kotlin
> @file:Suppress("PackageDirectoryMismatch")
> 
> package android.content.res;
> 
> class RestringTypedArray : TypedArray() {
> 
>     override fun getText(index: Int): CharSequence {
>         return super.getText(index)
>     }
> }
> ```
> 
> In short the java compiler doesn't check if your package directive matches the actual file location. You can use this "feature" in all kinds of ways, many other java/kotlin features are based on this fact.

on Android 12，crash by: `java.lang.NoSuchMethodError: No direct method <init>()V in class Landroid/content/res/TypedArray; or its super classes (declaration of 'android.content.res.TypedArray' appears in /system/framework/framework.jar)`

**Comment by MirkoWu** [comment]
I cannot instantiate `RestringTypedArray`
