### ISSUE TITLE
Restring memory leak

### ISSUE THREAD

**Issue by rprunskas** [B3nedikt/restring#114]
It looks like Restring leaks activity context. if I remove this code from activity code, leaks disappears.

```
   private val appCompatDelegate: AppCompatDelegate by lazy {
        ViewPumpAppCompatDelegate(
            baseDelegate = super.getDelegate(),
            baseContext = this,
            wrapContext = { baseContext -> Restring.wrapContext(baseContext) }
        )
    }

    override fun getDelegate(): AppCompatDelegate {
        return appCompatDelegate
    }
```

┬───
│ GC Root: System class
│
├─ android.view.inputmethod.InputMethodManager class
│    Leaking: NO (InputMethodManager↓ is not leaking and a class is never
│    leaking)
│    ↓ static InputMethodManager.sInstance
├─ android.view.inputmethod.InputMethodManager instance
│    Leaking: NO (DecorView↓ is not leaking and InputMethodManager is a
│    singleton)
│    ↓ InputMethodManager.mCurRootView
├─ android.view.ViewRootImpl instance
│    Leaking: NO (DecorView↓ is not leaking)
│    mContext instance of com.android.internal.policy.DecorContext, wrapping
│    activity lt.testapp.activity.main_activity.MainActivity with
│    mDestroyed = false
│    ViewRootImpl#mView is not null
│    mWindowAttributes.mTitle = "[lt.testapp.dev/lt.testapp](http://lt.testapp.dev/lt.testapp).
│    activity.main_activity.MainActivity"
│    mWindowAttributes.type = 1
│    ↓ ViewRootImpl.mView
├─ com.android.internal.policy.DecorView instance
│    Leaking: NO (View↓ is not leaking and View attached)
│    View is part of a window view hierarchy
│    View.mAttachInfo is not null (view attached)
│    View.mWindowAttachCount = 1
│    mContext instance of com.android.internal.policy.DecorContext, wrapping
│    activity lt.testapp.activity.main_activity.MainActivity with
│    mDestroyed = false
│    ↓ ViewGroup.mChildren
├─ android.view.View[] array
│    Leaking: NO (View↓ is not leaking)
│    ↓ View[2]
├─ android.view.View instance
│    Leaking: NO (View attached)
│    View is part of a window view hierarchy
│    View.mAttachInfo is not null (view attached)
│    View.mID = R.id.null
│    View.mWindowAttachCount = 1
│    mContext instance of com.android.internal.policy.DecorContext, wrapping
│    activity lt.testapp.activity.main_activity.MainActivity with
│    mDestroyed = false
│    ↓ View.mResources
│           ~~~~~~~~~~
├─ dev.b3nedikt.restring.internal.RestringResources instance
│    Leaking: UNKNOWN
│    Retaining 2,7 MB in 48111 objects
│    ↓ RestringResources.resourcesDelegate$delegate
│                        ~~~~~~~~~~~~~~~~~~~~~~~~~~
├─ kotlin.SynchronizedLazyImpl instance
│    Leaking: UNKNOWN
│    Retaining 2,6 MB in 47874 objects
│    ↓ SynchronizedLazyImpl._value
│                           ~~~~~~
├─ dev.b3nedikt.restring.internal.ResourcesDelegate instance
│    Leaking: UNKNOWN
│    Retaining 2,6 MB in 47873 objects
│    context instance of dev.b3nedikt.restring.internal.RestringContextWrapper
│    ↓ ResourcesDelegate.context
│                        ~~~~~~~
├─ dev.b3nedikt.restring.internal.RestringContextWrapper instance
│    Leaking: UNKNOWN
│    Retaining 2,6 MB in 47864 objects
│    mBase instance of androidx.appcompat.view.ContextThemeWrapper
│    RestringContextWrapper does not wrap a known Android context
│    ↓ ContextWrapper.mBase
│                     ~~~~~
├─ androidx.appcompat.view.ContextThemeWrapper instance
│    Leaking: UNKNOWN
│    Retaining 2,6 MB in 47862 objects
│    mBase instance of android.app.ContextImpl
│    ContextThemeWrapper does not wrap a known Android context
│    ↓ ContextWrapper.mBase
│                     ~~~~~
├─ android.app.ContextImpl instance
│    Leaking: YES (ContextImpl.mOuterContext is an instance of lt.
│    testapp.activity.main_activity.MainActivity with Activity.mDestroyed
│    true)
│    Retaining 2,6 MB in 47846 objects
│    mAutofillClient instance of lt.testapp.activity.main_activity.
│    MainActivity with mDestroyed = true
│    mOuterContext instance of lt.testapp.activity.main_activity.
│    MainActivity with mDestroyed = true
│    ↓ ContextImpl.mAutofillClient
╰→ lt.testapp.activity.main_activity.MainActivity instance
​     Leaking: YES (ObjectWatcher was watching this because lt.testapp.
​     activity.main_activity.MainActivity received Activity#onDestroy()
​     callback and Activity#mDestroyed is true)
​     Retaining 2,6 MB in 47545 objects
​     key = 616aa0ec-a701-4425-a894-2f21f9789e44
​     watchDurationMillis = 6233
​     retainedDurationMillis = 1228
​     mApplication instance of lt.testapp.PildykApp
​     mBase instance of dev.b3nedikt.restring.internal.RestringContextWrapper

**Comment by B3nedikt** [comment]
I would need more info on this one to help. Please recreate the issue in a fork of this repository by modifying the sample app so it reproduces the problem.

**Comment by B3nedikt** [comment]
Closed due to inactivity, feel free to reopen if still relevant :)

**Comment by rprunskas** [comment]
So it turns out that to replicate this issue, activity must be recreated when changing night mode. I've added code in forked repository which reproduces the issue.

Steps to replicate:
1. Open app, click "Toggle night mode" button.
2. Wait for leak canary notification about memory leak and click on notification to view the leak.

Repository:
https://github.com/rprunskas/restring?organization=rprunskas&organization=rprunskas

Branch:
leak

**Comment by B3nedikt** [comment]
I just clone it and tried it. I could not reproduce the issue. Could it be that the issue only appears with specific devices or depends on the android version?

**Comment by rprunskas** [comment]
Toggle might not work correctly, try to click two times, if background slightly changes then night mode was changed. I replicated with Xaiomi mi 12 - android 12 and android emulator 13.

**Comment by B3nedikt** [comment]
Yeah, it only occurs on android >= 12 it seems, and only after multiple clicks. Also the leak is always a different one xD I am unsure what causes it, I think I might look into it on the weekend though. When you find anything, feel free to comment or create a PR :)

**Comment by rprunskas** [comment]
It seems I fixed that memory leak, but not sure if you need updated example app :) 

https://github.com/B3nedikt/restring/pull/116

**Comment by B3nedikt** [comment]
Nah, not really, I think that would confuse other users more then it helps ;)
I just changed it in another release with a few other small changes, and released it as restring 5.2.2.
I mention you in the release for attribution, I could not cherry pick from the UI as github removed that feature a year ago.
Anyway please check if the new release also fixes the issue in your production app ;)

**Comment by rprunskas** [comment]
It works, thank you :)

**Comment by B3nedikt** [comment]
You're welcome :)
