### ISSUE TITLE
Library does not supports "sr_RS" locale.

### ISSUE THREAD

**Issue by RaginiSingh** [B3nedikt/restring#115]
I am trying to load translations for sr_RS locale but its loading default locale.

**Comment by B3nedikt** [comment]
I would need more info on this one to help. Please recreate the issue in a fork of this repository by modifying the sample app so it reproduces the problem. Then just link it to this issue. If you work on open source, you can also just link the project of course ;)

**Comment by B3nedikt** [comment]
Closed due to inactivity, feel free to reopen if still relevant :)
