### ISSUE TITLE
Lint issue post addition of this library

### ISSUE THREAD

**Issue by nileshkoo** [B3nedikt/restring#119]
Lint is flagging below two errors post addition of this library.

issue id="NewApi" severity="Error" message="Call requires API level 24 (current min is 21): `java.lang.Iterable#forEach`" category="Correctness"

issue id="RememberReturnType" severity="Error" message="`remember` calls must not return `Unit`" category="Correctness"

Could you please let me know what should be done to get it away?
Thanks!

**Comment by B3nedikt** [comment]
Neither of these two APIs is used by restring, so I can only guess ;)
If you want you can try to reproduce this issues in a fork of restring by modifying the example app so it reproduces your issue. I would assume it is due to some other library you use, not directly related to restring.

**Comment by B3nedikt** [comment]
Closed, feel free to reopen if still relevant :)

**Comment by nileshkoo** [comment]
This got fixed by upgrading the AGP from 7.1.3 to 7.3.1. Thanks.
