### ISSUE TITLE
ANR triggered by slow operations in main thread

### ISSUE THREAD

**Issue by liandara** [B3nedikt/restring#123]
Hi, a month ago i was upgrade this library in my project to solve problem about RestringResource.kt Line 162 mentioned there is no resource found. I think it's work after i put the override function getReources() on MyApplication class like this solved issue [https://github.com/B3nedikt/restring/issues/103] .

Unfortunately, this solution create new issue on my Firebase Crashlytics, where is the code above have been **triggered the ANR because the process take a long time on main thread**.

Have you faced the same issue? or might be yo have the solution to fix this issue.

I would really appreciate your help. Thank you 🙏

**Comment by B3nedikt** [comment]
Hi :) This should not trigger the ANR, the code in the `getResources()` is just wrapping an object, it does not do any processing. Do you have a stacktrace?

**Comment by B3nedikt** [comment]
I would need more input to help with this issue, feel free to reopen if you find out anything more. You can try to reproduce the issue by forking this repository and modifying its example app so that it reproduces the problem.
