### ISSUE TITLE
High performance cost for overriding `Application#getResources()` with `Restring.wrapResources()`

### ISSUE THREAD

**Issue by JedLee6** [B3nedikt/restring#126]
`Application#getResources()`  overridden with `Restring.wrapResources()` will create a bran-new Instance of `RestringResources`, when `Application#getResources()`  is called everytime.

Hi, @B3nedikt .Can I override `Application#attachBaseContext()` with `Restring.wrapContext()` rather than overriding `Application#getResources()` with `Restring.wrapResources()` ? As its `getResources()` would return a fixed Instance of `RestringResources`.

But I encountered `ClassCastException: RestringContextWrapper cannot be cast to android.app.ContextImpl` problem when I override `Application#attachBaseContext()` with `Restring.wrapContext()`  on My Samsung S21 on Android12.

Can I cache the first created RestringResources instance like below? Thank you in advance for your help!

```kotlin
class ExampleApplication : Application() {
    //...
    private var restringResources: Resources? = null
    override fun getResources(): Resources {
        if (restringResources == null) {
            restringResources = Restring.wrapResources(applicationContext, super.getResources())
        }
        return restringResources!!
    }
}
```

**Comment by B3nedikt** [comment]
Yes, that `ClassCastException` will occur whenever you try to cast to `ContextImpl` if you overwrite `attachBaseContext`. Some popular libraries like Firebase as well as some android API like BroadcastReceiver rely on this cast for some of their functionality, so I would normally not recommend interfering with it. Depending on your app it might be possible though.

Caching as an optimization is certainly possible here. Your code could also be written like this:
```kotlin
class ExampleApplication : Application() {

//...
    private val wrappedResources by lazy {
        Restring.wrapResources(applicationContext, super.getResources())
    }
//...
    override fun getResources(): Resources = wrappedResources
}
```

I question how much of a performance benefit this will actually bring you though. The wrap function does only do minimal initialization stuff, it should not be that heavy. Did you benchmark this?

**Comment by JedLee6** [comment]
Hi, @B3nedikt . Thank you for your help and advice!
I didn't benchmark the performance benefit. But when I test my app, `Application#getResources()` overridden with `Restring.wrapResources()` will create about ten different RestringResources instances per seconds. So I'm worried about the performance cost of creating so many instances frequently.

I came up with another cache solution, which is trying to avoid the problem that strings retrieved from the ApplicationContext will no longer change. I'm not quite sure if it's feasible, so I'm really looking forward to your advice!

```Kotlin
object Restring {

    private var restringResources: RestringResources? = null

    @JvmStatic
    fun wrapApplicationResources(context: Context, baseResources: Resources): Resources {
        if (this::stringRepository.isInitialized.not()) {
            return baseResources
        }
        if (baseResources is RestringResources) {
            return baseResources
        } else if (baseResources == restringResources?.baseResources) {
            //If the `baseResources` are equal, use the cached `RestringResources`
            return restringResources!!
        } else {
            RestringResources(baseResources, stringRepository, context).apply {
                restringResources = this
                return this
            }
        }
    }

}
```

**Comment by B3nedikt** [comment]
You're welcome :) Yeah, this optimization should always work. I doubt it will bring any relevant performance benefit, even with ten different instances, as all these instances just wrap the same reference, but I don't think it should have any downsides either.
