### ISSUE TITLE
How can TypedArray be proxied?

### ISSUE THREAD

**Issue by MirkoWu** [B3nedikt/restring#127]
This is possible to implement, but would take quite a bit of work. In short you would need to modify the `obtainTypedArray(...)` method of the `ResourcesWrapper`, to return a `TypedArray` which returns texts from the `StringRepository`. This custom `TypedArray` would need to overwrite the `getText()` method.

In short you are looking at 1-2 days of programming, which I don't have the time right now to do on the side ;) If this feature is important to you, feel free to implement it and submit a PR though :)

I think your workaround is fine, another alternative would be a custom Reword `ViewTransformer`, just look at my repository for an example.

_Originally posted by @B3nedikt in https://github.com/B3nedikt/restring/issues/111#issuecomment-1272321230_

**Comment by MirkoWu** [comment]
hello,May I ask if this feature is currently implemented? ResourcesImpl is hidden, and ResourcesImpl.ThemeImpl cannot be extends, and other classes or methods are `final`.

**Comment by B3nedikt** [comment]
No, this is currently not implemented, you would need to use a workaround as described in the issue you cited.

Also you are correct in assuming that an implementation using ResourcesImpl would not work, which would in theory be the ideal solution of course, as it would mean that you could just use obtainStyledAttributes. You could wrap TypedArray as described in the issue though, and have obtainTypedArray() return that wrapped Array which returns texts from Restring. But as I wrote, such an wrapper is currently not implemented, so you would need to use another workaround.

If you have another idea, feel free to suggest it though, I take PRs :)
