### ISSUE TITLE
Can you provide the ability to provide custom return values when "override val strings: MutableMap<Locale, MutableMap<String, CharSequence>>" does not have a corresponding key, but the XML file has a key.

### ISSUE THREAD

**Issue by gnmmdk** [B3nedikt/restring#133]
For example, title: It is possible that there is no corresponding key in the map, but the XML does. In this case, Restirng will directly use the value corresponding to the XML resource file. For this scenario, we want to display other content, such as determining whether the key is in ABCD format_ Is the length of the key at the beginning 13? If the condition is met, use the key directly as the displayed value. If the condition is not met, still display the value in the XML.

**Comment by gnmmdk** [comment]
Hello, brother, can you reply?

**Comment by B3nedikt** [comment]
Sure brother ;)
In short this can be done by using a custom repository, something along the lines of this:
```kotlin
Restring.stringRepository = YourCustomRepository(...)
```
You would still need to implement this class entirely by yourself, you can take some inspiration from the repository classes in the project to do so. I could also add some functionality to simplify this, the question is how such an API should look like, to be reasonable generic.

I think something like this would be an option:
```kotlin
class CachedStringRepository(
    val persistentRepository: MutableStringRepository,
    interceptStrings: (id: String) -> String?,
    interceptsPlurals: ...
) : MutableStringRepository {
```
Here the intercept methods would enable you to check a condition like if there is no corresponding key in the map but in the XML like in your example. And then if you condition is met, return a custom value, else return null, so that the repository will work as normal. This should be implemented in a way to work for all types of resource supported by restring: strings, quantity strings & string arrays. Maybe add this functionality to a different class then CachedStringRepository, as to not have too much functionality in it.
Feel free to suggest an alternative though. If you want to implement something like this yourself I also take PRs.

**Comment by B3nedikt** [comment]
Also a more generic implementation should consider the Locale, so maybe something like this:
```kotlin
class CachedStringRepository(
    val baseRepository: MutableStringsRepository,
    interceptStrings: (locale: Locale, id: String) -> String?,
    interceptQuantityStrings: ...
) : MutableStringRepository {
```

**Comment by gnmmdk** [comment]
ok，thanks～

**Comment by gnmmdk** [comment]
Additionally, I would like to ask for advice on how to clean up data in cache files.

I have set 'Restring. stringRepository. toMutableRepository(). strings. clear(); Restring. putStrings (local, AppStringsGenerator. getStrings (local))'.

The location is the same, but the value obtained is the result of 'the second value overwrites the first'. The effect I want is to clear it and even if the location is the same, only the subsequent values will be obtained.

**Comment by B3nedikt** [comment]
Hm, that should be the current behaviour if I understand you correctly. Can you clone this repository, create a failing unit tests that reproduces the problem, and link your fork to this issue?

**Comment by gnmmdk** [comment]
The compilation of this project failed, but the problem is easy to reproduce.

Setting Restricting. put for the first time (local, {"key1": "value1", "key2": "value2"})

Set Restricting. put (location, {"key2": "value3", "key4": "value4"}) for the second time, and the two locations are the same.

Thus, the values of Restricting. stringRepository. toMutableRepository(). strings [local] are {"key1": "value1", "key2": "value3", "key4": "value4"}. What I want is {"key2": "value3", "key4": "value4"}. During the second setup, I also used Restring. stringRepository. toMutableRepository(). strings. clear()

**Comment by gnmmdk** [comment]
I have modified the source code as follows:
interface StringRepository {
    ...
    fun delete(key: Locale)

    fun  deleteAll()
}

class SharedPrefsStringRepository(
        private val sharedPreferencesProvider: (sharedPreferencesName: String) -> SharedPreferences
) : MutableStringRepository {
    ...


    override fun  delete(key: Locale){
        if(strings is LocalizedResourcesPersistentMap){
            strings.delete(key)
        }
        if(quantityStrings is LocalizedResourcesPersistentMap){
            quantityStrings.delete(key)
        }
        if(stringArrays is LocalizedResourcesPersistentMap){
            stringArrays.delete(key)
        }
    }

    override fun  deleteAll(){
        if(strings is LocalizedResourcesPersistentMap){
            strings.deleteAll()
        }
        if(quantityStrings is LocalizedResourcesPersistentMap){
            quantityStrings.deleteAll()
        }
        if(stringArrays is LocalizedResourcesPersistentMap){
            stringArrays.deleteAll()
        }
    }
}

Use it this way:
![image](https://github.com/B3nedikt/restring/assets/18391426/59c44ccb-b3f7-4a0e-b7c7-a32f303d2b0e)

**Comment by B3nedikt** [comment]
Your delete method should be implemented like this, no need to create custom repository:
```kotlin
Restring.stringRepository.toMutableRepository().strings[Locale.ENGLISH]?.clear()
```
So you just need this:
```kotlin
    @Test
    fun clearShouldDeleteAllStrings() {

        val strings = mapOf("key1" to "value1", "key2" to  "value2")
        val strings2 = mapOf("key2" to "value3", "key4" to  "value4")

        Restring.stringRepository.toMutableRepository().strings[Locale.ENGLISH]?.putAll(strings)
        Restring.stringRepository.toMutableRepository().strings[Locale.ENGLISH]?.clear()
        Restring.stringRepository.toMutableRepository().strings[Locale.ENGLISH]?.putAll(strings2)

        Restring.stringRepository.toMutableRepository().strings[Locale.ENGLISH]!! shouldContainSame strings2
    }
```
The project compiles perfectly with the current android Studio version.

**Comment by gnmmdk** [comment]
Okay, thank you very much
