### ISSUE TITLE
Custom control, invalid after initializing setText (Spannable)

### ISSUE THREAD

**Issue by gnmmdk** [B3nedikt/restring#134]
class TestTextView @JvmOverloads constructor(
    context: Context, attrs: AttributeSet? = null
) : AppCompatTextView(context, attrs)  {
    init {
        text = createServiceAgreementText()
    }
    /**
     * 
     * <p>
     * Author: zhuanghongzhan
     * Date: 2021-10-21
     */
    private fun createServiceAgreementText(): Spannable {
        val content ="You can read \"User Agreement\" and \"Privacy Policy Statement\" learn more"
        val span = SpannableStringBuilder(content)
        val userText = "\"User Agreement\""

        val userClickableSpan: NoUnderLineClickableSpan = object : NoUnderLineClickableSpan() {
            override fun onClick(widget: View) {
                //打开隐私协议页面
              //todo
            }
        }
        setServiceSpan(span, content, userText, userClickableSpan)
        return span

    }

    /**
     * Set clicks and colors
     * <p>
     * Author: zhuanghongzhan
     * Date: 2021-10-21
     * @param span SpannableStringBuilder
     * @param content String
     * @param subText String
     * @param clickSpan NoUnderLineClickableSpan
     */
    private fun setServiceSpan(span: SpannableStringBuilder, content: String, subText: String, clickSpan: NoUnderLineClickableSpan) {
        val start = content.indexOf(subText)
        span.setSpan(clickSpan, start, start + subText.length, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE)

        val userColorSpan = ForegroundColorSpan(R.color.color_5590F6.color())
        span.setSpan(userColorSpan, start, start + subText.length, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE)

    }
}
-----
As mentioned above, I set the text highlighting and click event, but after connecting to Restring, this function is no longer valid.

**Comment by gnmmdk** [comment]
open class NoUnderLineClickableSpan : ClickableSpan() {
    override fun onClick(widget: View) {
        //...
    }

    override fun updateDrawState(ds: TextPaint) {
        ds.isUnderlineText = false
    }
}

**Comment by B3nedikt** [comment]
In short you need to feed Restring something that it can persist without loosing information, e.g. you could use `Html.fromHtml` . If you want something which can help with your concret example, I would need more input though. Can you fork this repository, and change the code so that it reproduces your problem, then link it to this issue?

If you already have a potential solution, you can also create a PR.

**Comment by B3nedikt** [comment]
Solved I guess? Feel free to reopen if it still doesn't work for you.
