### ISSUE TITLE
Activity cannot inherit AppCompatActivity, and Android: text="@ string/key" cannot take effect. How to solve it?

### ISSUE THREAD

**Issue by gnmmdk** [B3nedikt/restring#136]
My project contains Flutter and needs to inherit FlutterFragmentActivity(), so I cannot set AppCompatDelegate.

**Comment by B3nedikt** [comment]
You would need to give in the wrapped context, and it should work I think. But I am not sure about your architecture, can you create a minimal sample app which shows how you use restring with flutter?
Just fork this repository, and modify it so that it works as closely as your real app as possible.

**Comment by gnmmdk** [comment]
Equivalent to inheriting FragmentActivity, how to handle this situation? Can I give you a demo

**Comment by gnmmdk** [comment]
“You would need to give in the wrapped context, and it should work” How to achieve it? Thank you.

**Comment by B3nedikt** [comment]
You can just provide the context to the flutter engine:
```kotlin
    val wrappedContext = Restring.wrapContext(this)
    val flutterEngine = FlutterEngine(wrappedContext)
```
You should ideally do this in your application class.

If you also do some native android stuff, you can also add this to your application class:

```kotlin
    override fun getResources(): Resources {
        return Restring.wrapResources(applicationContext, super.getResources())
    }
```

And this to your activities:
```kotlin
    override fun attachBaseContext(newBase: Context) {
        super.attachBaseContext(Restring.wrapContext(newBase))
    }
```

Ideally I would recommend to put the flutter stuff into a separate `Fragment`, and have the activity inherit from `AppCompatActivity` though, this should make things easier. I don't have a demo for anything like that, I hope this does give you some ideas though ;) If you need more details, you would need to provide me with a sample app, as I cannot guess the architecture of your app.

**Comment by gnmmdk** [comment]
I want to submit a new branch to you, but I do not have permission:
14:26:12.985: [restring] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/feature/test_fragment:feature/test_fragment
remote: Permission to B3nedikt/restring.git denied to gnmmdk.
fatal: unable to access 'https://github.com/B3nedikt/restring.git/': The requested URL returned error: 403
--------------------------
I uploaded it to my own warehouse and the link is here:https://github.com/gnmmdk/restring
FragmentActivity is set, but it does not take effect：
    override fun getResources(): Resources {
        return Restring.wrapResources(applicationContext, super.getResources())
    }

    override fun attachBaseContext(newBase: Context) {
        super.attachBaseContext(Restring.wrapContext(newBase))
    }

**Comment by gnmmdk** [comment]
Calling DialogFragment in FragmentActivty also has no effect. Can you help me with this issue? Also in the project I posted：https://github.com/gnmmdk/restring

**Comment by B3nedikt** [comment]
Looks good, you are just missing the AppCompatDelegate in the `TestFragmentActivity`. Something like this will do the trick:
```kotlin
        val delegate = AppCompatDelegate.create(this, this);
        ViewPumpAppCompatDelegate(delegate, this, Restring::wrapContext).installViewFactory()
```
Also your `TestFragmentActivity` needs to implement `AppCompatCallback`. Just add something like this:
```
class TestFragmentActivity : FragmentActivity(), AppCompatCallback {

...

    override fun onSupportActionModeStarted(mode: ActionMode?) = Unit

    override fun onSupportActionModeFinished(mode: ActionMode?) = Unit

    override fun onWindowStartingSupportActionMode(callback: ActionMode.Callback?): ActionMode? = null
}
```

Does this work for you?

**Comment by B3nedikt** [comment]
Ah, and looking at your code again, you don't need to wrap the context in the `FragmentActivity`. So the whole code should look like this:
```kotlin
class TestFragmentActivity : FragmentActivity(), AppCompatCallback {

    override fun onCreate(savedInstanceState: Bundle?) {
        val delegate = AppCompatDelegate.create(this, this);
        ViewPumpAppCompatDelegate(delegate, this, Restring::wrapContext).installViewFactory()
        super.onCreate(savedInstanceState)
        
        setContentView(R.layout.fragment_activity_test)
        findViewById<View>(R.id.show_dialog_fragment).setOnClickListener{
            TestDialog().show(supportFragmentManager,"dialog")
        }
    }

    override fun getResources(): Resources {
        return Restring.wrapResources(applicationContext, super.getResources())
    }

    override fun onSupportActionModeStarted(mode: ActionMode?) = Unit

    override fun onSupportActionModeFinished(mode: ActionMode?) = Unit

    override fun onWindowStartingSupportActionMode(callback: ActionMode.Callback?): ActionMode? = null
}
```

**Comment by gnmmdk** [comment]
FragmentActivity cannot set AppCompatDelegate. This method is not effective for me.

**Comment by B3nedikt** [comment]
This code does not set the `AppCompatDelegate`, it just creates a `AppCompatDelegate` and installs its `ViewFactory` into a `FragmentActivity`. The delegate itself is not used. `FragmentActivity` can use the `ViewFactory` fro app compat just fine.

**Comment by B3nedikt** [comment]
Closed due to inactivity.

**Comment by gnmmdk** [comment]
Can you provide a demo about FragmentActivty access？thanks～

**Comment by B3nedikt** [comment]
There is a demo in the code I posted above, just copy it into your code :)

**Comment by gnmmdk** [comment]
I'm sorry, I didn't read your reply carefully before. Thank you very much
