### ISSUE TITLE
Frequent issues with automatic and associated startup.

### ISSUE THREAD

**Issue by gnmmdk** [B3nedikt/restring#137]
The Xiaomi application market has detected frequent self startup or associated startup of applications, which has led to the failure of applications to be launched. It seems to be related to ViewPumpAppCompatDelegate. May I ask if this problem can be solved?
[Uploading 57f0534cfc13436fb43d85340b8cb3d6.xlsx…]()

**Comment by gnmmdk** [comment]
[57f0534cfc13436fb43d85340b8cb3d6.xlsx](https://github.com/B3nedikt/restring/files/13261816/57f0534cfc13436fb43d85340b8cb3d6.xlsx)

**Comment by B3nedikt** [comment]
This is not related with the ViewPumpAppCompatDelegate, it does not influence self startup. Have you checked the Tencent Beacon API you are using?

**Comment by gnmmdk** [comment]
I have also consulted with official personnel regarding the Tencent TBS SDK. The reason is that Tencent TBS automatically starts and then calls to create an activity, and then calls ViewPumpAppCompatDelegate?

**Comment by B3nedikt** [comment]
Yeah, ViewPumpAppCompatDelegate gets called whenever an activity gets created.
