### ISSUE TITLE
Collapsed, seems to be a problem with Restirng. Can you help me take a look?

### ISSUE THREAD

**Issue by gnmmdk** [B3nedikt/restring#138]
Bugly's error log is as follows:

![image](https://github.com/B3nedikt/restring/assets/18391426/acf6da74-b6b4-4e28-822c-6634823ec85b)

# main(1)

android.content.res.Resources$NotFoundException

String resource ID #0x2060009

1
java.lang.RuntimeException:Error receiving broadcast Intent { act=com.xxxx.xxxxx.GPU_PROFILER_START flg=0x400010 pkg=com.vv.work } in org.chromium.content.browser.TracingControllerAndroid$TracingBroadcastReceiver@94ca07c
2
android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52560(LoadedApk.java:1326)
3
......
4
Caused by:
5
android.content.res.Resources$NotFoundException:String resource ID #0x2060009
6
android.content.res.Resources.getText(Resources.java:339)
7
android.content.res.Resources.getString(Resources.java:433)
8
dev.b3nedikt.restring.internal.ResourcesDelegate.java.lang.String getString(int)(ResourcesDelegate.java:50)
9
dev.b3nedikt.restring.internal.RestringResources.java.lang.String getString(int)(RestringResources.java:42)
10
android.content.Context.getString(Context.java:556)
11
org.chromium.content.browser.TracingControllerAndroid.startTracing(TracingControllerAndroid.java:200)
12
org.chromium.content.browser.TracingControllerAndroid$TracingBroadcastReceiver.onReceive(TracingControllerAndroid.java:1157)
13
android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52560(LoadedApk.java:1316)
14
android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7(Unknown Source:4)
15
android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run(Unknown Source:39)
16
android.os.Handler.handleCallback(Handler.java:790)
17
android.os.Handler.dispatchMessage(Handler.java:99)
18
android.os.Looper.loop(Looper.java:164)
19
android.app.ActivityThread.main(ActivityThread.java:6536)
20
java.lang.reflect.Method.invokeImpl(Native Method)
21
java.lang.reflect.Method.invoke(Method.java:411)
22
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:468)
23
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:808)

**Comment by B3nedikt** [comment]
Hard to tell what is going on. Restring & ViewPump do explicitly exclude `WebView`s, so normally as crash as above cannot occur assuming you set everything up as in the Readme. Can you post code which demonstrates how you integrate your `WebView`?

**Comment by B3nedikt** [comment]
Closed due to inactivity.
