### ISSUE TITLE
android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by gnmmdk** [B3nedikt/restring#139]
I found the following error reported on the startup page on some models:

11-13 16:40:46.177 30981 32071 E system_server: No package ID 7f found for ID 0x7f130135.
11-13 16:40:46.178 30981 31870 I mtkpower_client: perf_lock_rel, hdl:225614, tid:31870
11-13 16:40:46.179 30981 32071 D ColorAppStartupManager: launchAppByActivity has exception! 
11-13 16:40:46.179 30981 32071 D ColorAppStartupManager: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f130135
11-13 16:40:46.179 30981 32071 D ColorAppStartupManager: 	at android.content.res.ResourcesImpl.getResourceEntryName(ResourcesImpl.java:331)
11-13 16:40:46.179 30981 32071 D ColorAppStartupManager: 	at android.content.res.Resources.getResourceEntryName(Resources.java:2246)
11-13 16:40:46.179 30981 32071 D ColorAppStartupManager: 	at com.android.server.am.ColorAppStartupManager.launchAppByActivity(ColorAppStartupManager.java:613)
11-13 16:40:46.179 30981 32071 D ColorAppStartupManager: 	at com.android.server.am.ColorAppStartupManager.isBlockUnnoticeableActivity(ColorAppStartupManager.java:601)
11-13 16:40:46.179 30981 32071 D ColorAppStartupManager: 	at com.android.server.am.ColorAppStartupManager.shouldPreventStartActivity(ColorAppStartupManager.java:2338)
11-13 16:40:46.179 30981 32071 D ColorAppStartupManager: 	at com.android.server.am.ColorAppStartupManager.shouldPreventStartActivity(ColorAppStartupManager.java:2370)
11-13 16:40:46.179 30981 32071 D ColorAppStartupManager: 	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1101)
11-13 16:40:46.179 30981 32071 D ColorAppStartupManager: 	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:818)
11-13 16:40:46.179 30981 32071 D ColorAppStartupManager: 	at com.android.server.wm.ActivityTaskManagerService.startActivityAndWait(ActivityTaskManagerService.java:1486)
11-13 16:40:46.179 30981 32071 D ColorAppStartupManager: 	at com.android.server.am.ActivityManagerService.startActivityAndWait(ActivityManagerService.java:4048)
11-13 16:40:46.179 30981 32071 D ColorAppStartupManager: 	at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:567)
11-13 16:40:46.179 30981 32071 D ColorAppStartupManager: 	at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:189)
11-13 16:40:46.179 30981 32071 D ColorAppStartupManager: 	at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
11-13 16:40:46.179 30981 32071 D ColorAppStartupManager: 	at android.os.ShellCommand.exec(ShellCommand.java:44)
11-13 16:40:46.179 30981 32071 D ColorAppStartupManager: 	at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:11476)
11-13 16:40:46.179 30981 32071 D ColorAppStartupManager: 	at android.os.Binder.shellCommand(Binder.java:936)
11-13 16:40:46.179 30981 32071 D ColorAppStartupManager: 	at android.os.Binder.onTransact(Binder.java:820)
11-13 16:40:46.179 30981 32071 D ColorAppStartupManager: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:5256)
11-13 16:40:46.179 30981 32071 D ColorAppStartupManager: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3174)
11-13 16:40:46.179 30981 32071 D ColorAppStartupManager: 	at com.android.server.am.OppoActivityManagerService.onTransact(OppoActivityManagerService.java:169)
11-13 16:40:46.179 30981 32071 D ColorAppStartupManager: 	at android.os.Binder.execTransactInternal(Binder.java:1166)
11-13 16:40:46.179 30981 32071 D ColorAppStartupManager: 	at android.os.Binder.execTransact(Binder.java:1130)
11-13 16:40:46.179 30981 31870 I mtkpower_client: perf_lock_acq, hdl:225614, dur:0, num:10, tid:31870
11-13 16:40:46.179 30981 32071 W System.err: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f130135
11-13 16:40:46.179 30981 32071 W System.err: 	at android.content.res.ResourcesImpl.getResourceEntryName(ResourcesImpl.java:331)
11-13 16:40:46.179 30981 32071 W System.err: 	at android.content.res.Resources.getResourceEntryName(Resources.java:2246)
11-13 16:40:46.179 30981 32071 W System.err: 	at com.android.server.am.ColorAppStartupManager.launchAppByActivity(ColorAppStartupManager.java:613)
11-13 16:40:46.179 30981 32071 W System.err: 	at com.android.server.am.ColorAppStartupManager.isBlockUnnoticeableActivity(ColorAppStartupManager.java:601)
11-13 16:40:46.179 30981 32071 W System.err: 	at com.android.server.am.ColorAppStartupManager.shouldPreventStartActivity(ColorAppStartupManager.java:2338)
11-13 16:40:46.179   800   846 I libPowerHal: [perfLockRel] hdl:225614, idx:0
11-13 16:40:46.179 30981 32071 W System.err: 	at com.android.server.am.ColorAppStartupManager.shouldPreventStartActivity(ColorAppStartupManager.java:2370)
11-13 16:40:46.179   800   846 I libPowerHal: [PD] scn:0 hdl:225614 lock_user:system_server pid:30981 tid:31870 dur:0
11-13 16:40:46.179 30981 32071 W System.err: 	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1101)
11-13 16:40:46.180 30981 32071 W System.err: 	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:818)
11-13 16:40:46.180   800   846 I libPowerHal: [PD] system_server update cmd:10000100 param:2
11-13 16:40:46.180 30981 32071 W System.err: 	at com.android.server.wm.ActivityTaskManagerService.startActivityAndWait(ActivityTaskManagerService.java:1486)
11-13 16:40:46.180 30981 32071 W System.err: 	at com.android.server.am.ActivityManagerService.startActivityAndWait(ActivityManagerService.java:4048)
11-13 16:40:46.180 30981 32071 W System.err: 	at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:567)
11-13 16:40:46.180 30981 32071 W System.err: 	at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:189)
11-13 16:40:46.180 30981 32071 W System.err: 	at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
11-13 16:40:46.180 30981 32071 W System.err: 	at android.os.ShellCommand.exec(ShellCommand.java:44)
11-13 16:40:46.180 30981 32071 W System.err: 	at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:11476)
11-13 16:40:46.180 30981 32071 W System.err: 	at android.os.Binder.shellCommand(Binder.java:936)
11-13 16:40:46.180 30981 32071 W System.err: 	at android.os.Binder.onTransact(Binder.java:820)
11-13 16:40:46.180 30981 32071 W System.err: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:5256)
11-13 16:40:46.180 30981 32071 W System.err: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3174)
11-13 16:40:46.180 30981 32071 W System.err: 	at com.android.server.am.OppoActivityManagerService.onTransact(OppoActivityManagerService.java:169)
11-13 16:40:46.180 30981 32071 W System.err: 	at android.os.Binder.execTransactInternal(Binder.java:1166)
11-13 16:40:46.180 30981 32071 W System.err: 	at android.os.Binder.execTransact(Binder.java:1130)
11-13 16:40:46.180 30981 32071 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.xxx.xxx/com.xxx.xxx.xxx.ui.activity.WelcomeActivity mCallingUid=2000} from uid 2000 and from pid 13764

It is possible that the res. getString of the final call system will throw an exception, so does it need to be captured here?
![image](https://github.com/B3nedikt/restring/assets/18391426/b260a830-5f61-4a5d-9d89-16d2a9288ad4)

**Comment by B3nedikt** [comment]
Yes, of course it will throws an exception if the string does not exist. You should normally not try to catch this exception, as there must be a reason why the string you want to retrieve does not exist in the `Resources` instance. You should try to find out this reason, instead of just catching the exception. Without knowing more about your code, I can't really help out here though ;)

**Comment by B3nedikt** [comment]
@gnmmdk One this that just came to my mind which could be helpful: 7F is the application package id, so it seems you are trying to retrieve something from the application resources, which does not exist. You could actually remove restrings initialization from the `Application` class, if you don't use the application `Resources` to retrieve strings anywhere, but only the `Resources` from the activity `Context`. Just remove this:

```kotlin
class SampleApplication : Application() {

    ...

    override fun getResources(): Resources {
        return Restring.wrapResources(applicationContext, super.getResources())
    }
}
```

**Comment by B3nedikt** [comment]
Closed due to inactivity.
