### ISSUE TITLE
@abdelmalek-roshdi This is not a problem, you just need to set the package correctly. Something like this should do it:

### ISSUE THREAD

**Issue by MirkoWu** [B3nedikt/restring#140]
@abdelmalek-roshdi This is not a problem, you just need to set the package correctly. Something like this should do it:

```kotlin
@file:Suppress("PackageDirectoryMismatch")

package android.content.res;

class RestringTypedArray : TypedArray() {

    override fun getText(index: Int): CharSequence {
        return super.getText(index)
    }
}
```
In short the java compiler doesn't check if your package directive matches the actual file location. You can use this "feature" in all kinds of ways, many other java/kotlin features are based on this fact.

_Originally posted by @B3nedikt in https://github.com/B3nedikt/restring/issues/111#issuecomment-1300535042_

**Comment by MirkoWu** [comment]
on Android 12，crash by: java.lang.NoSuchMethodError: No direct method <init>()V in class Landroid/content/res/TypedArray; or its super classes (declaration of 'android.content.res.TypedArray' appears in /system/framework/framework.jar)
I cannot instantiate RestringTypedArray。 log:Accessing hidden method Landroid/content/res/TypedArray;-><init>()V (blocked, linking, denied)

**Comment by B3nedikt** [comment]
You can fix this error by including the following library in your project: [FreeReflection](https://github.com/tiann/FreeReflection).

I would not really recommend using `TypedArray`s with Restring though, it will be a bit hacky and hard to implement. You can use the `Reword` `ViewTransformer` API instead, see [here](https://github.com/B3nedikt/reword) how to use it for custom views. Or just use `getString(...)` as usual if you have access to the source code of the custom view you want to use with Restring.

**Comment by B3nedikt** [comment]
Solved I guess, feel free to reopen if you have further questions :)
