### ISSUE TITLE
application.getResources in Robolectric environment

### ISSUE THREAD

**Issue by Kamkalet** [B3nedikt/restring#142]
Hi, 

when I try to run Robolectric tests, it uses `app.getResources` method to init all stuff beforehand. But appContext is still null. So is there any problem to change in my App class usage of `applicationContext` simply  to `this`? No sure but it might be also an issue in Robolectric side.

Result:

    override fun getResources(): Resources {
        return Restring.wrapResources(this, super.getResources())
    }

**Comment by B3nedikt** [comment]
No, it should not make any difference, you can safely use it!

I would not call it an issue on Robolectric side, as Robolectric is only supposed to work closely like a real device, not the same way. Or else you could just use integration tests and run on a real device.
