### ISSUE TITLE
languageTag is not working in SharedPrefsStringRepository

### ISSUE THREAD

**Issue by SoftXperience** [B3nedikt/restring#144]
I'm testing on Android 13, API 33 emulator and there are several Locale's where the languageTag method returns "und" (undetermined).

For example de_AT and nl_BE, so the strings aren't correctly persisted with the SharedPrefsStringRepository. The last locale with result "und" will overwrite the previous. And also loading fails because "und" can't be converted back into a Locale.

Because the LocaleUtil and other classes are internal, I can't simply inherit and overwrite the behaviour. So would be nice if you can have a look for it and fix it.

I can also provide a pull request if you like. I would just not use languageTag...

**Comment by B3nedikt** [comment]
Interesting issue, fixed with the latest version :)
First release for this library after two years xD

**Comment by neustaTerasa** [comment]
Yeah, I was afraid the project might be abandoned. Thanks for the quick fix, let's me get rid of copied classes from internal.
