### ISSUE TITLE
Language with Region fallback not working

### ISSUE THREAD

**Issue by neustaTerasa** [B3nedikt/restring#149]
Hi,
another fallback issue happens if you provide uncomplete translations for a specific region.

For example:
values-de
<string name="login">Login</string>
<string name="logout">Logout</string>

values-de-rAT
<string name="login">Login starten</string>

If I use the string "logout", it won't be found in restring strings, so ResourcesDelegate get's null and falls back to system resources which will deliver the value from "de".

But if I updated "de" also with restring, this updated value won't be used.

Same would happen for the fallback to default language ("values" folder), but as I can't programmatically figure out which language is used as default, I guess that's not fixable.

**Comment by B3nedikt** [comment]
Hi :) Looks like a good change to me, I adjusted your PR a bit, to also take quantity strings and string arrays into account and made the behaviour configureable by the user. Please have a look if it suits your needs.

I will release this as a new major version, as it is a albeit small behaviour change.

**Comment by neustaTerasa** [comment]
Great, looks good. Thank you!

**Comment by B3nedikt** [comment]
You're welcome :) Fixed with version 6.0.0, please try it out!
