### ISSUE TITLE
Hello, the xml file to introduce a custom view, and then setting the title doesn't look like it works

### ISSUE THREAD

**Issue by wllj** [B3nedikt/restring#152]

**Comment by B3nedikt** [comment]
Are you referring to something from the example app?

**Comment by wllj** [comment]
.xml
<declare-styleable name="SelectItemView">
        <attr name="siv_title" format="string" />
</declare-styleable>

I wrote my own demo, then defined a View myself and set the title(SelectItemView)
    String title = typedArray.getString(R.styleable.SelectItemView_siv_title)
    setTitle(title);

Setting in xml
<com.....view.SelectItemView
    app:siv_title="@string/location" />

But Restring doesn't work, do you have any suggestions or what is wrong with me.thank you！

**Comment by B3nedikt** [comment]
Restring does not support typed arrays. Please just use context.getString(...) instead. Does this help you?
