### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter map

### ISSUE THREAD

**Issue by ronem123** [B3nedikt/restring#22]
My String loader class  has getStrings() method like this. I have a collections of languages and the strings associated with the languages from the remote server. I saved the key value for all the language into the shared preference and the below method 

    ConstantMethods.getHashMap(context, lng);

will returns the key,value for the selected locale.

    @NotNull
    @Override
    public Map<String, CharSequence> getStrings(@NotNull Locale locale) {
        String lng = locale.getLanguage();
        Log.v("Called","Language is "+lng);
        Map<String, String> lngMap = ConstantMethods.getHashMap(context, lng);
        Log.v("Called","Total Contented in ap "+lngMap.size());
        Map<String, CharSequence> lngCharMap = new HashMap<>();

        try {
            for (Map.Entry<String, String> entry : lngMap.entrySet()) {
                String key = entry.getKey();
                CharSequence value = entry.getValue();
                Log.v("Called", "Key " + key);
                Log.v("Called", "Value " + value);
                lngCharMap.put(key, value);
            }
        }catch (Exception e){
            e.printStackTrace();
        }

        //this is just to check only ignore this for loop
        for (Map.Entry<String, CharSequence> entry : lngCharMap.entrySet()) {
            String key = entry.getKey();
            CharSequence value = entry.getValue();
            Log.v("Called","KeyChar "+key);
            Log.v("Called","ValueChar "+value);
        }
        Log.v("Called","TotalContentedChar "+lngCharMap.size());

        return lngCharMap;
    }

With [Restring](https://github.com/hamidness/restring)  it was working fine but then I got an issues in  android 7 as not updating languages,  so I chose to use your library and now I am facing the error saying. 

Note : All the logs are printing messages properly.

    Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter map
        at kotlin.collections.MapsKt__MapsKt.plus(Maps.kt)
        at dev.b3nedikt.restring.StringsLoaderTask.loadStrings(StringsLoaderTask.kt:43)
        at dev.b3nedikt.restring.StringsLoaderTask.doInBackground(StringsLoaderTask.kt:27)
        at dev.b3nedikt.restring.StringsLoaderTask.doInBackground(StringsLoaderTask.kt:14)
        at android.os.AsyncTask$2.call(AsyncTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:760)

**Comment by B3nedikt** [comment]
You are probably doing something like this in your StringsLoader:
```
    @NotNull
    @Override
    public Map<String, Map<PluralKeyword, CharSequence>> getQuantityStrings(@NotNull Locale locale) {
        return null;
    }

    @NotNull
    @Override
    public Map<String, CharSequence[]> getStringArrays(@NotNull Locale locale) {
        return new HashMap<>();
    }
```

It should be like this:
```
    @NotNull
    @Override
    public Map<String, Map<PluralKeyword, CharSequence>> getQuantityStrings(@NotNull Locale locale) {
        return new HashMap<>();
    }

    @NotNull
    @Override
    public Map<String, CharSequence[]> getStringArrays(@NotNull Locale locale) {
        return new HashMap<>();
    }
```
That should fix the crash.

In short these two methods don´t support null, you need to return an empty hash map. I will improve this by adding default implementations for these methods for java users. Does this fix your issue?

**Comment by ronem123** [comment]
Thanks for quick reply I will soon look into it.

**Comment by B3nedikt** [comment]
You´re welcome! You may now also just update to the latest version, and delete the two methods, they have default implementations now.

**Comment by B3nedikt** [comment]
I assume this is fixed for you, if you face any more problems, feel free to open a new issue.
