### ISSUE TITLE
Update string at runtime on Fragment 

### ISSUE THREAD

**Issue by ganatrajay** [B3nedikt/restring#28]
Hi,

for Fragment will this below work ?

val rootView = window.decorView.findViewById<ContentFrameLayout>(android.R.id.content)
        Reword.reword(rootView)

please let me know thanks

**Comment by B3nedikt** [comment]
No, correct would be like this:
```kotlin
        val rootView = requireActivity()
            .window
            .decorView
            .findViewById<ContentFrameLayout>(android.R.id.content)

        Reword.reword(rootView)
```

**Comment by CasperLindbergAtGithub** [comment]
@B3nedikt where do you call this from? I have a fragment with data binding and don't know where to call it from:

`override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        val view = super.onCreateView(inflater, container, savedInstanceState)
        // FROM HERE? on WHAT?
        mViewLifeCycleOwner = viewLifecycleOwner
        uiUpdater = ViewModelProvider(this).get(UiUpdater::class.java)
        return view
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        // FROM HERE? on WHAT?
    }`

**Comment by rajlabana** [comment]
@B3nedikt how can this be implemented on a Fragment via Java code, as I have tried a few methods and it is not working.
On theOnCreateView & onViewCreated I have the following lines:
Restring.putString(Locale, stringMap);
Reword.reword(rootView)

This is not working. The above is the only code that I have on the fragment page. The Activity calling said fragment defines the getDelagte()

**Comment by B3nedikt** [comment]
@rajlabana In java it looks like this:
```java
final View rootView = requireActivity()
        .getWindow()
        .getDecorView()
        .findViewById(android.R.id.content);

Reword.reword(rootView);
```

**Comment by rajlabana** [comment]
@B3nedikt  this does not appear to be working have implemented in Fragment like this:

`@Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        
        Restring.putStrings(Locale.ENGLISH, new HomeActivity.SampleStringsGenerator().getStrings(Locale.ENGLISH));
        final View rewordView = requireActivity()
                .getWindow()
                .getDecorView()
                .findViewById(android.R.id.content);
        Reword.reword(rewordView);
}`
