### ISSUE TITLE
Updating strings via Data Binding

### ISSUE THREAD

**Issue by CasperLindbergAtGithub** [B3nedikt/restring#29]
I have a ViewModel and a corresponding layout using the instructionText field as its text as below:

`private val _instructionText = MutableLiveData("Not set")
    val instructionText: LiveData<String> = _instructionText`

When I update` _instructionText.value = app.getString(R.string.hello)`
I need to in some way Reword.reword(layout) but I cannot access the layout file from the ViewModel and even with a trick to access it from the fragment it doesn't work.

**Comment by B3nedikt** [comment]
You should in general not try to perform any kind of interaction with the view from the ViewModel, but from the Fragment.
Something like this would be more according to the MVVM pattern:
```kotlin
        viewModel.instructionText.observe(viewLifecycleOwner, Observer {
            
            binding.instructionText.text = it
            
            val rootView = requireActivity()
                .window
                .decorView
                .findViewById<ContentFrameLayout>(android.R.id.content)

            Reword.reword(rootView)
        })
```

**Comment by ganatrajay** [comment]
Hey 

thanks for the reply but i m using fragment which extends basefragment class and ya let me try this

**Comment by B3nedikt** [comment]
So from my understanding this works for you now. If not feel free to open another issue :)
