### ISSUE TITLE
Getting string values which do not exist in strings.xml

### ISSUE THREAD

**Issue by edgar-zigis** [B3nedikt/restring#30]
Hello,

first of all thank you for this amazing library, it's really great. 

I would like to ask a question whether it is possible to use strings with this library which do not exist within the strings.xml by simply querying context? We use this context extension for querying resource by name, however it seems not to return Restring loaded strings although the right context is used. 
```
fun Context.getStringResourceByName(id: String): String? {
    val resId = resources?.getIdentifier(id, "string", packageName)
    return if (resId != null && resId != 0) {
        getString(resId)
    } else {
        null
    }
}
```
The string which is queried does not exist in strings.xml, but it is present in StringLoader.
Sure, we could use a workaround to use the loaded strings directly from our persisted database, but it would be nice to have a possibility to get it straight from the context.

Thank you for the answer!

**Comment by B3nedikt** [comment]
Thanks, you´re welcome :)

Actually you´re code could be shortened to this:

```
fun Context.getStringResourceByName(id: String): String? {
    val resId = resources.getIdentifier(id, "string", packageName)
    return if (resId != 0) {
        getString(resId)
    } else {
        null
    }
}
```

Resources should not be null at this point, or else you are very likely calling the code from somewhere wrong ;)
getIdentifier will always return null at the moment, as the identifier does not exist, as it is not in your strings.xml.
I fixed this by generating ids if they don´t exist in a new version of restring I released just now. Please try it out if it works for you!

**Comment by edgar-zigis** [comment]
It works, awesome! Thank you! 👍
