### ISSUE TITLE
Is there any way to support locale change on all activity at the stack?

### ISSUE THREAD

**Issue by kaiyan910** [B3nedikt/restring#32]
say for example I have MainActivity and SettingsActivity inside the stack,
I change my locale at SettingsActivity, does MainActivity's text change automatically or 
I need to call another Reword.reword(rootView) by myself to change the text on MainActivity?

What do you suggest to implement such scenario? thanks!

**Comment by B3nedikt** [comment]
If you just resume the other activity its text will not change automatically. Calling it by yourself is probably the best way to use reword in a multi activity app. I would just add the call to reword to your BaseActivity if you have one:

```
abstract class BaseActivity : AppCompatActivity() {

    override fun attachBaseContext(newBase: Context) {
        super.attachBaseContext(ViewPumpContextWrapper.wrap(Restring.wrapContext(newBase)))
    }

    override fun getResources(): Resources {
        return Restring.wrapContext(baseContext).resources
    }

    override fun onResume() {
        super.onResume()

        val rootView = window.decorView.findViewById<ContentFrameLayout>(android.R.id.content)
        Reword.reword(rootView)
    }
}
```

Also you need to call Reword directly after changing the Locale in the SettingsActivity of course. An other thing to consider are if you set strings dynamically from activities and not from XML, these need to be updated automatically. You will need to update these in onResume(). Also you need to take care to set the action bar title in onResume() if you set action bar titles not from the layout files using Toolbar but directly through the manifest.

I think Restring & Reword are easier to use with a Single Activity application, but they should work for your scenario as well :)

**Comment by kaiyan910** [comment]
thanks for the support i will try on it!
