### ISSUE TITLE
Occasional crash with lateinit stringRepository

### ISSUE THREAD

**Issue by edgar-zigis** [B3nedikt/restring#40]
Some of my users get this crash occasionally:

```
Caused by kotlin.UninitializedPropertyAccessException: lateinit property stringRepository has not been initialized
       at dev.b3nedikt.restring.Restring.wrapContext(Restring.java:66)
       at com.paysera.core.base.BaseActivity.attachBaseContext(BaseActivity.java:170)
```
Android versions are different, but devices are no-name Huawei Y6II or Samsung J6, A50, A70.
It might be that the Android OS there behave a bit differently, because I got weird crashes on these devices before.

**Comment by B3nedikt** [comment]
I think this was due to a rare race condition that should be fixed in restring 5.0.0. Should you still encounter it in the new version, open the issue again ;)
