### ISSUE TITLE
Bug with "\n" line separator symbol

### ISSUE THREAD

**Issue by hkarimka** [B3nedikt/restring#45]
If any string contains a character "\n", then this string is shown with this character. A line break should be added, but only the character itself is displayed.
For example: I have `String str = "Hello! \n How are you?";`
I do `Restring.setString(Locale.getDefault(), "key", str);`
What I expect to see in my application:
**"Hello!
How are you?"**
What I actially see:
**"Hello! \n How are you?**

**Comment by B3nedikt** [comment]
Hi @hkarimka, you are using an API from Restring 4, which actually took only strings. You are trying to pass a CharSequence here, which will not work. You could achieve what you want with the StringsLoader, or just switch to the latest version of my lib, restring 5, which has a much cleaner API ;)

**Comment by hkarimka** [comment]
I'm sorry, but I updated my library to the version 5.0.1, but it still doesn't work.. I get my strings from Cloud Firestore, I get string 
"Hello! \n How are you?", I call Restring.putStrings(locale, mapWithThisString), and I see on my screen:
**"Hello! \n How are you?"**. If I disable Restring and load bundled strings, then I see what actually I should:
**"Hello!
How are you?"**

**Comment by aliaziada** [comment]
Hi 
I'm facing the same problem with \n and i'm using latest version of lib

**Comment by D3laru3** [comment]
Same problem with the Restring version 5.1.4. I have also problems with characters like &amp;.
