### ISSUE TITLE
Using Restring 5.0.1 breaks the build

### ISSUE THREAD

**Issue by hkarimka** [B3nedikt/restring#48]
I used Restring 4.0.5 earlier, and today, when I migrated to Restring 5.0.1, my build failed with the error:
'let((T) -> R): R' is only available since Kotlin 1.3.50 and cannot be used in Kotlin 1.3'
and other similar errors.
If I use version 4.0.5, then everything is OK.

**Comment by B3nedikt** [comment]
If this is no issue for you I would recommend to update to the latest kotlin version 1.4.10, that should make stuff easier ;)
Other than that as Restring 5 is a new major version the API has changed so it is expected that it brakes your build. You need to migrate to Restring 5 if you want to use the new features including support for appcompat 1.2.0. Just go through this repositories Readme ;)
