### ISSUE TITLE
Add option to store selected locale

### ISSUE THREAD

**Issue by alexKatona** [B3nedikt/restring#49]
Currently locale is always used from system at app start as Locale.getDefault.
It would be nice to create something like:

from:
`   Restring.locale = locale`
to:
`Restring.setLocale(locale= Locale("en"), isPermanent=true)`

so next time I open the app it would use the previously selected language

**Comment by B3nedikt** [comment]
@alexKatona I did not add this on purpose to the core library, as many people might not need it. You can however use my library [https://github.com/B3nedikt/AppLocale](AppLocale) to do this. Look here for an integration example:
[https://github.com/B3nedikt/restring#app-locale-integration](AppLocale Integration)

This library by default stores the locale in the SharedPreferences, but changing it to the EncryptedSharedPreferences should be trivial ;)
