### ISSUE TITLE
Add option to provide custom shared preferences

### ISSUE THREAD

**Issue by alexKatona** [B3nedikt/restring#50]
It would be nice to add an option to provide custom shared preferences instance. For example if I would like to store them in encrypted shared prefences from jetpack.

**Comment by B3nedikt** [comment]
Restring 5.1.0 provides the SharedPrefsStringRepository for this use case now ;)

**Comment by alexKatona** [comment]
Thanks for the quick update, good job :) 
@B3nedikt

**Comment by B3nedikt** [comment]
You're welcome :)
