### ISSUE TITLE
Translation does not work with CollapsingToolbarLayout

### ISSUE THREAD

**Issue by oussama-reguez** [B3nedikt/restring#55]
Hey, the Title of CollapsingToolbarLayout does not translate unless I do it programmatically which will require a lot of refactoring, i'm using  restring:5.1.0, viewpump:3.0.1 and reword:2.0.0

**Comment by edgar-zigis** [comment]
Hey, maybe using ViewTransformers is an option? We use them for custom views too.
Example:

```
object OpaqueToolbarViewTransformer : AbstractViewTransformer<OpaqueToolbar>() {

    private const val ATTRIBUTE_TITLE_TEXT = "titleText"

    override val viewType = OpaqueToolbar::class.java

    override val supportedAttributes = setOf(
        ATTRIBUTE_TITLE_TEXT
    )

    override fun OpaqueToolbar.transform(attrs: Map<String, Int>) {
        attrs.forEach {
            when (it.key) {
                ATTRIBUTE_TITLE_TEXT -> titleText = resources.getString(it.value)
            }
        }
    }
}
```

**Comment by B3nedikt** [comment]
@oussama-reguez A custom ViewTransformer as suggested by @edgar-zigis is the solution here. If you want you can make a PR to [Reword](https://github.com/B3nedikt/reword) & I include this in the lib. As CollapsingToolbarLayout is a very common custom view this would be a good addition. For completely custom views only in your code base or stuff from non google libs, you need to write support for it yourself.

**Comment by B3nedikt** [comment]
@oussama-reguez I added support for the CollapsingToolbarLayout in Reword 2.0.1.
