### ISSUE TITLE
Compare parameters "%d" and "%s" from strings

### ISSUE THREAD

**Issue by hkarimka** [B3nedikt/restring#60]
Hi! Thank you so much, we use your library and it's very useful!
But it's possible to get a situation when we have a different number of parametres and their types in strings.xml and in dynamic strings.
For example, we have in strings.xml: 
"Hi %s! Do you want to know what's new in HelloApp version %d?"
And we decided to change this in dynamic strings to:
"Hi %s! Do you want to know what's new in %s version %d?"
Of course, application will crash in this case. I think, it would be fine to compare new (dynamic) strings and bundled strings, get quantity and queue of parametres and apply new strings only in case if they are equal.
What do you think?

P.S.: integer numbers can be applied to float parameters as %.0f, but float numbers can't be applied to integer parameters %d.

**Comment by B3nedikt** [comment]
You're welcome :)
I don't think that would be a good change for the library. As you mention, normally one would expect that strings from the string repository are actually correct. Assuming somebody actually made a mistake and added a string with the wrong number of parameters to restring for whatever reason, not throwing an error would lead to this mistake not getting noticed.

If you are sure however that the bundled strings are always a valid fallback, I would recommend to just implement this on your application side. When you add the dynamic strings to Restring, e.g. with Restring.putStrings() just check for all strings if they contain parameters, and if these parameters are incorrect just filter them so the broken dynamic strings don't get added to Restring. Then Restring will use the bundled string, leading to the behavior you want. While this does add some overhead to whenever you add the strings to Restring, it saves some overhead whenever a formatted string is queried, so I think this is also form this perspective the better solution. Also this overhead is saved for all people who do not need this feature.

What do you think about this?

**Comment by hkarimka** [comment]
Okay, thank you! 
I agree.
