### ISSUE TITLE
ViewPump issue: dev.b3nedikt.viewpump.ViewPumpContextWrapper cannot be cast to android.app.ContextImpl

### ISSUE THREAD

**Issue by onebird100** [B3nedikt/restring#61]
I have two test devices, a Pixel 2 (API 24) and a Samsung J1 (API 19). The app works fine on API 24 but I get the following error on API 19, every single time without fail.

`"java.lang.RuntimeException: Unable to start receiver androidx.work.impl.background.systemalarm.ConstraintProxyUpdateReceiver: java.lang.ClassCastException: dev.b3nedikt.viewpump.ViewPumpContextWrapper cannot be cast to android.app.ContextImpl\n\tat android.app.ActivityThread.handleReceiver(ActivityThread.java:2674)\n\tat android.app.ActivityThread.access$1700(ActivityThread.java:166)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loop(Looper.java:136)\n\tat android.app.ActivityThread.main(ActivityThread.java:5590)\n\tat java.lang.reflect.Method.invokeNative(Native Method)\n\tat java.lang.reflect.Method.invoke(Method.java:515)\n\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1280)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1096)\n\tat dalvik.system.NativeStart.main(Native Method)\nCaused by: java.lang.ClassCastException: dev.b3nedikt.viewpump.ViewPumpContextWrapper cannot be cast to android.app.ContextImpl\n\tat android.app.ActivityThread.handleReceiver(ActivityThread.java:2664)\n\t... 10 more\n"`

I am able to send a full crash log if it helps. I saw your last release of viewpump (3.0.1) was meant to address crashes on older devices, so I'm not sure if this is the kind of crash you were referring to. 

I have done the following in the mean-time, but it's not exactly a permanent solution:

 
  ```
  @Override
    protected void attachBaseContext(Context newBase) {
        if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            super.attachBaseContext(ViewPumpContextWrapper.wrap(Restring.wrapContext(newBase)));
        }
        else super.attachBaseContext(newBase);
    }
    
    @Override
    public Resources getResources() {
        if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            return Restring.wrapContext(getBaseContext()).getResources();
        }
        else  return super.getResources();
    }
```

[crash.log](https://github.com/B3nedikt/restring/files/5469283/crash.log)

**Comment by B3nedikt** [comment]
No, the fixes in 3.0.1 refer to other crashes. This one is new to me, there seem to be some similar ones on android < 5 though, mainly the fault of some issues with appcompat. Which version of appcompat are you using?

I am working on a ViewPump version which works better with newer versions of appcompat at the moment, it should fix issues like the above.

**Comment by onebird100** [comment]
I'm in appcompat 1.2.0

` implementation 'androidx.appcompat:appcompat:1.2.0'`

I think I can wait for a new version. The majority of my users are on newer android versions, so it's not a big issue yet

**Comment by B3nedikt** [comment]
@onebird100 This issue should be fixed with the latest version of ViewPump & Reword, I documented the update in this repositories Readme.
