### ISSUE TITLE
[FEATURE] show string key instead of value

### ISSUE THREAD

**Issue by alexKatona** [B3nedikt/restring#62]
Hello, a common use case for testers is to check which string key was used in the app. The most helpful way is to show string keys instead of their values 

so in case

string name = "dashboard_title"  >Dashboard< 

would show the dashboard_title. Do.you think it's feasible to maybe pass such a Boolean in init of restring

**Comment by B3nedikt** [comment]
While this sounds useful just passing in a boolean is not really a generic solution, and I don't want to overload the init method more then necessary. I am looking into something like a interceptor feature, where you can just change whatever the resources return. This will be part of the next iteration of restring. This should take a while though, as I am working on some other stuff as well ;)

For now I think you could either just add the strings keys as values when inserting strings into the repository, or use a custom repository for tests. This could look like this:

```
class TestRepository(context: Context) : MutableStringRepository {

    private val delegate = CachedStringRepository(
            SharedPrefsStringRepository { sharedPreferencesName ->
                context.getSharedPreferences(sharedPreferencesName, Context.MODE_PRIVATE)
            }
    )

    private val testStrings by lazy {
        val fields = R.string::class.java.fields
        val stringNames = fields.map { it.name }

        AppLocale
                .supportedLocales
                .associateWith { stringNames.associateWith { it as CharSequence }.toMutableMap() }
                .toMutableMap()
    }

    override val supportedLocales: Set<Locale>
        get() = delegate.supportedLocales

    override val strings: MutableMap<Locale, MutableMap<String, CharSequence>>
        get() = testStrings

    override val quantityStrings: MutableMap<Locale, MutableMap<String, Map<PluralKeyword, CharSequence>>>
        get() = delegate.quantityStrings

    override val stringArrays: MutableMap<Locale, MutableMap<String, Array<CharSequence>>>
        get() = delegate.stringArrays

}
```

Set this in your application with Restring.stringRepository whenever you are in test mode. Just for inspiration something I typed together in five minutes though, there may be other better ways specific for your application ;)

**Comment by alexKatona** [comment]
thanks for the workaround, works fine as well
