### ISSUE TITLE
Crashes using version 5.0.1

### ISSUE THREAD

**Issue by hkarimka** [B3nedikt/restring#63]
Hello! Thank you for your library!
But I get a lot of issues using the version 5.0.1 with exception:
```
Caused by java.lang.NullPointerException
Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter defType
dev.b3nedikt.viewpump.internal.-ViewPumpLayoutInflater$WrapperFactory2ViewCreator.onCreateView (-ViewPumpLayoutInflater.kt:390)
dev.b3nedikt.viewpump.internal.-FallbackViewCreationInterceptor.intercept (-FallbackViewCreationInterceptor.kt:14)
dev.b3nedikt.viewpump.internal.-InterceptorChain.proceed (-InterceptorChain.kt:30)
dev.b3nedikt.reword.RewordInterceptor.intercept (RewordInterceptor.kt:13)
dev.b3nedikt.viewpump.internal.-InterceptorChain.proceed (-InterceptorChain.kt:30)
dev.b3nedikt.viewpump.ViewPump.inflate (ViewPump.kt:38)
dev.b3nedikt.viewpump.internal.-ViewPumpLayoutInflater$WrapperFactory2.onCreateView (-ViewPumpLayoutInflater.kt:365)
```

And also:
```
Caused by android.content.res.Resources$NotFoundException
File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f070060
android.content.res.Resources.loadDrawableForCookie (Resources.java:2579)
android.content.res.Resources.loadDrawable (Resources.java:2468)
android.content.res.MiuiResources.loadDrawable (MiuiResources.java:394)
android.content.res.Resources.getDrawable (Resources.java:834)
dev.b3nedikt.restring.internal.RestringResources.getDrawable (RestringResources.kt:111)
android.content.Context.getDrawable (Context.java:412)
androidx.core.content.ContextCompat.getDrawable (ContextCompat.java:455)
```

Could you please check and help? 
A lot of crashes from Huawei devices Y3 2017 and Y6 Prime 2018 using Android 6.0 and 8.0,
Thank you!

**Comment by B3nedikt** [comment]
The first one will be fixed with the next ViewPump patch version, the second crash I did not encounter before. 
The second crash is not related to Restring I think, if you remove Restring it will still crash. Can you post the code of the "abc_vector_test.xml"? Maybe it contains a gradient tag or something else that is not supported on Android 6.0 or MiUi?

Also is there any reason you use Restring 5.0.1 and not the latest 5.1.0?

**Comment by hkarimka** [comment]
Okay, thank you!
Sorry for the bothering with the second crash then!
Yes, I am going to update from 5.0.1 to 5.1.0, but I will update when the new version of ViewPump library is ready, I think.

**Comment by hkarimka** [comment]
Hi! When will you release the new version of ViewPump library?
Thank you!

**Comment by B3nedikt** [comment]
@hkarimka I just released it :) Both ViewPump & reword changed, just look at the new Readme of this repository on how to integrate them.

**Comment by hkarimka** [comment]
Thank you!
But you change your library initialization and usage too much... With every new version of the library it is neccesary to rewrite code using Restring. But anyway, thank you! :)
