### ISSUE TITLE
how to exclude text in recycleview

### ISSUE THREAD

**Issue by Alfonso88** [B3nedikt/restring#65]
Is there an option exclude some object, ie: values in recycleview etc

I need to rebind again the values in recycleview or viewmodels, if not restring update the values into default text 

Thank for your library anyway

**Comment by B3nedikt** [comment]
You're welcome :) From my understanding you want to exclude some views from getting changed when calling Reword.reword. This is currently not possible.

One way to add this would be adding callback to Reword.reword like this:

```kotlin
Reword.reword(parentView, interceptUpdate = { view ->

if(view is RecyclerView) {
     return true
}
return false
}
```

Would this be helpful for you?

**Comment by Alfonso88** [comment]
thank you for your response, it helps a lot thx
