### ISSUE TITLE
Getting string value from strings.xml which do not exist in StringRepository

### ISSUE THREAD

**Issue by jstr14** [B3nedikt/restring#66]
Hello,

I'm checking your library and I have some questions. My goal is combine your library with some Localizable strings api to download a resource file with translations and save and access it by your library and if the string not exists on StringRepository get value from `strings.xml` file.

Checking all library features I don't see anything about get string value from Strings.xml if your StringRepository not contains that key. 

Is it possible?

Thank you!

**Comment by B3nedikt** [comment]
Yeah, that works. In short:

- If a string exists in the stringRepository use it, the id will be the same as the one generated in your R.strings file
- If a string exists in the stringRepository but not in Strings.xml, Restring will generate a "managed" Id for it and use this to reference the string
- If a string does not exist in stringRepository but in Strings.xml, use the one from strings.xml
- Only if a string neither exists in the stringRepository or the strings.xml a ResourceNotFound exception will get thrown. 

This is somewhat hidden documented in the [Notes](https://github.com/B3nedikt/restring#notes) section ;)
