### ISSUE TITLE
OutOfMemory Crash

### ISSUE THREAD

**Issue by shanejmurphy** [B3nedikt/restring#76]
Caused by java.lang.OutOfMemoryError
Failed to allocate a 1843212 byte allocation with 1381456 free bytes and 1349KB until OOM
dalvik.system.VMRuntime.newNonMovableArray (VMRuntime.java)
androidx.appcompat.app.ViewPumpAppCompatDelegate$createView$1.invoke (ViewPumpAppCompatDelegate.java:27)
dev.b3nedikt.viewpump.internal.InterceptorChain.proceed (InterceptorChain.java:26)
dev.b3nedikt.reword.RewordInterceptor.intercept (RewordInterceptor.java:34)
dev.b3nedikt.viewpump.internal.InterceptorChain.proceed (InterceptorChain.java:37)
androidx.appcompat.app.ViewPumpAppCompatDelegate.inflate (ViewPumpAppCompatDelegate.java:82)
androidx.appcompat.app.ViewPumpAppCompatDelegate.onCreateView (ViewPumpAppCompatDelegate.java:68)
io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$WrapperFactory2ViewCreator.onCreateView (-ViewPumpLayoutInflater.java:378)
io.github.inflationx.viewpump.internal.-FallbackViewCreationInterceptor.intercept (-FallbackViewCreationInterceptor.java:14)
io.github.inflationx.viewpump.internal.-InterceptorChain.proceed (-InterceptorChain.java:30)
io.github.inflationx.calligraphy3.CalligraphyInterceptor.intercept (CalligraphyInterceptor.java:18)
io.github.inflationx.viewpump.internal.-InterceptorChain.proceed (-InterceptorChain.java:30)
io.github.inflationx.viewpump.ViewPump.inflate (ViewPump.java:36)
io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$WrapperFactory2.onCreateView (-ViewPumpLayoutInflater.java:358)
android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:776)
android.view.LayoutInflater.inflate (LayoutInflater.java:525)
io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate (-ViewPumpLayoutInflater.java:57)
android.view.LayoutInflater.inflate (LayoutInflater.java:427)
io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate (-ViewPumpLayoutInflater.java:48)
android.view.LayoutInflater.inflate (LayoutInflater.java:378)
androidx.appcompat.app.AppCompatActivity.setContentView (AppCompatActivity.java:170)

Looking at the logs on this, it looks as though this happens when the app goes through a long period of use. In my case, over 60 screens were opened. The call to setContentView() kicked off the crash

**Comment by B3nedikt** [comment]
This sounds like a memory leak. It is hard to tell though if it is the fault of restring, the error only shows that the memory runs out during view inflation, which is likely because inflating views may often mean a big memory allocation especially if they contain lots of bitmaps.

Two questions here:
- Do you use LeakCanary? If you do check for leaks before the crash, and post a dump here if you find one.
- You use both my version of ViewPump as well as the original version at the same time. I guess the only reason for this is the Calligraphy library?

**Comment by shanejmurphy** [comment]
We dont have LeakCanary unfortunately but your assumption about ViewPump is correct. Is there something in this i wonder? I'll try investigate further and maybe install LeakCanary to give some better insights.
Feel free to close this issue. If my investigation raises anything related to your libraries Ill open a new issue.
Thanks

**Comment by B3nedikt** [comment]
@shanejmurphy Not sure, I checked Calligraphy out yesterday and hacked it to work with my version of viewpump. Took only like half and hour, but I would not recommend using calligraphy in general, as androidX now supports custom fonts out of the box. But an technically interesting library non the less xD

Anyway just include it like this:

```groovy
dependencies {
    // Legacy lib for custom fonts
    implementation 'dev.b3nedikt.calligraphy:calligraphy:4.0.2'

    // AndroidX compatibility
    implementation 'androidx.appcompat:appcompat:1.2.0'

    // Intercept view inflation
    implementation 'dev.b3nedikt.viewpump:viewpump:4.0.5'
}
```

And then all in you Application like this:

```java
        ViewPump.init(
                RewordInterceptor.INSTANCE,
                new CalligraphyInterceptor(
                        new CalligraphyConfig.Builder()
                                .setDefaultFontPath("fonts/Roboto-ThinItalic.ttf")
                                .setFontAttrId(R.attr.fontPath)
                                .setFontMapper(font -> font)
                                .build())
        );
}
```
See here: [Calligraphy](https://github.com/B3nedikt/Calligraphy)

Have fun debugging with LeakCanary, in my experience if you never used in an app before you will encounter and fix a lot of unrelated leaks before you find the ones which eat a lot of memory xD
Feel free to create a issue or open an PR if you find something in restring :)
