### ISSUE TITLE
Is there any way to detect change of the string from Manifest?

### ISSUE THREAD

**Issue by gibreelmart** [B3nedikt/restring#82]
I have my manifest like this:

` <meta-data
            android:name="com.veridiumid.sdk.LICENSE"
            android:value="@string/licence_veridium_sdk" />
        <meta-data
            android:name="com.veridiumid.sdk.fourf.LICENSE"
            android:value="@string/licence_veridium_fourf" />`

Reading your documentation i can change the strings, but my "component" get the string from the manifest/meta-data, but this never detect the change, is any way to do this?

Thanks!

**Comment by B3nedikt** [comment]
@gibreelmart I am not sure what you want to achieve exactly. But assuming you have any android component like a activity or a service, you can just retrieve the meta data from the application info, and perform a reverse lookup for the strings id using reflection over the R.string class. Then just look up this id using Restring.stringRepository.strings to get the changed string. Does this help you?
For anything more detailed I would need some code from you ;)

**Comment by B3nedikt** [comment]
Solved I guess ;)
