### ISSUE TITLE
Unable to update strings 

### ISSUE THREAD

**Issue by Eyal-Elbaz** [B3nedikt/restring#86]
Hi,
First, I want to thank you for the repo; sounds great. 
I have tried to update my strings XML using a translator like this
``

      Locale userLocale = new Locale(UserLanguage);
      translateStringsXML(getResources(), result -> { 
        Restring.putStrings(userLocale, result);
        Restring.setLocale(userLocale);
        System.out.println("Test :" + getString(R.string._date_of_birth_title));
        System.out.println("Test :" +
        Restring.getLocale());
        onLangSet.run();      
      });

But the restring doesn't work... even using the getString method.
I have chanked the "result" map she fine.
 
Thanks

**Comment by B3nedikt** [comment]
Glad you like it :)
You are misunderstanding what the putStrings(...) method does, it only provides the strings to restring. You need to then call other methods from restring to actually do something with these strings.
E.g. Restring.wrapContext(this).getString(R.string._date_of_birth_title) would achieve what you want to do above.

Please clone this repository and have a look at the sample app, it demonstrates how to use this library :)
