### ISSUE TITLE
Getting application crash on a specific layout

### ISSUE THREAD

**Issue by ashu5398** [B3nedikt/restring#87]
Hi I am getting a crash in reinflating textInputLayout. I have regenerated it [here](https://github.com/ashu5398/restring/tree/theme_crash) but am unable to debug on what actual issue is. can you please help?

**Comment by B3nedikt** [comment]
You are using MaterialComponents, but not a MaterialComponents Theme.

Something like this should fix it:

```xml

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>

```
