### ISSUE TITLE
How to use this library in dynamic feature module?

### ISSUE THREAD

**Issue by munnadroid** [B3nedikt/restring#88]
Since the library integration depends on the [Application class,](https://github.com/B3nedikt/restring#2-initialize) how to use this library in the dynamic feature module?

**Comment by B3nedikt** [comment]
While the applications class is the easiest way to integrate my library in your app and you can also use a custom Application class with dynamic feature modules using SplitCompat, a custom Application class it is not required for my lib to work.

If you want to use my lib without a custom application class you essentially need to wrap the context you use in your dynamic feature modules at some point. If you have a normal android app with XML files you can just wrap the context right before view inflation. I would need more information on your app architecture to give you a more detailed suggestion though ;)
