### ISSUE TITLE
Get string by locale

### ISSUE THREAD

**Issue by alexKatona** [B3nedikt/restring#89]
Hello,
I wanted to ask for your suggestion, how should i request a string in a desired locale. Lets say i use All the libs you have for locales, they are great btw 🙂, and i have selected  language/locale German  but i want to get a string in english like

LocaleManager.getStringForLocale(id :Int, locale :Locale)

Thanks for the suggestion in advance 🙂

I think i could get the reaource name by id, get the repoaitory fór the locale and find the string, fallbacking to compiled strings

**Comment by B3nedikt** [comment]
Hi, I am happy you like it :)

What you describe is the best way to do it I think, so something like this:

```kotlin
val stringName = context.resources.getResourceEntryName(R.string.title)
val string = Restring.stringRepository.strings[Locale.ENGLISH]?.get(stringName)
```

As you write you also need to fallback on compiled strings as string will obviously be null if you want to retrieve a string which has never been added to restring.
