### ISSUE TITLE
Empty repository

### ISSUE THREAD

**Issue by alexKatona** [B3nedikt/restring#90]
Hello, it seems like if there is an empty repository and I try to do something like
Restring.stringRepository.strings
        .mapKeys { it.key.toLanguageTag() }

it will throw the following error

https://discuss.kotlinlang.org/t/add-possibility-to-cast-emptymap-to-empty-instance-of-any-map-realization/5138/7
https://youtrack.jetbrains.com/issue/KT-20786

**Comment by B3nedikt** [comment]
I fixed this in restring 5.1.4 :)
